### ISSUE TITLE
running `source active combine` doesn't work

### ISSUE THREAD

**Issue by bibliotechy** [WSULib/combine-playbook#10]
In the fully provisioned vagrant box, with a running web app. 

I ssh into the machine.

I tried running `source active combine` as per the [quickstart](https://github.com/WSULib/combine/blob/dev/docs/quickstart.md#combine-python-environment) guide but that did not work. I had to run 
`source /usr/local/anaconda/bin/activate combine` in order to get the env set up.

**Comment by ghukill** [comment]
Thanks for noting this.  

I'm curious, did you ssh in via Vagrant using `vagrant ssh`?  I usually ssh in with `combine@192.168.45.10`, but just tried sshing with Vagrant and got the following:

```
-bash: activate: No such file or directo
```

If that was the case, good to know and we should update the documentation.  Haven't tried much as `vagrant` user from within the machine, think sshing in as, or su-ing to, `combine` makes interactions easier as most everything is owned by the `combine` user.

**Comment by ghukill** [comment]
Quickstart updated to account for both scenarios.

**Comment by bibliotechy** [comment]
Just to confirm that yes, I was using `vagrant ssh`. Definitely my usual practice for interacting with vagrant. 

:+1: for the fix
