### ISSUE TITLE
Create ansible template for combine localsettings.py

### ISSUE THREAD

**Issue by dcmcand** [WSULib/combine-playbook#22]
It would make configuration easier within ansible if localsettins.py was an ansible template, rather than the current method of using regex to replace values in an existing value.

**Comment by ghukill** [comment]
Agreed.  The only complexity I see will be being careful to upate the proposed template in this playbook repository, if and when the `localsettings.py.template` is updated in the [Combine repository](https://github.com/WSULib/combine).

e.g., will be merging these additions to `localsettings.py` fairly soon:
https://github.com/WSULib/combine/blob/stateio/combine/localsettings.py.template#L146-L153

When those updates are made, would require remembering to update them here as well, which isn't the end of the world, and as you've pointed out, would make manipulating that file *much* easier from ansible.  Which, for many, might be the only time it is manipulated.

But, all in all, still think it makes sense.
