### ISSUE TITLE
Deploying from Ubuntu to Ubuntu

### ISSUE THREAD

**Issue by ghukill** [WSULib/combine-playbook#5]
Also had a problem deploying *from* Ubuntu, suggesting that ssh was not working.  Had to set the following: `export SSH_AUTH_SOCK=0` before running `ansible`.

Not thoroughly tested or confirmed, but again, just noting.

**Comment by colehudson** [comment]
haven't been able to replicate this yet. I'll keep on trying though.

**Comment by ghukill** [comment]
Update: this might have been an issue with the host Ubuntu box, just for record keeping.

**Comment by colehudson** [comment]
Labeling as wontfix, but keeping issue active for a bit longer to see if it crops up again.

**Comment by colehudson** [comment]
Haven't seen this issue appear in the latest 9 months or so. Closing it for now.
